server:
    port: 8761  # Default : 8761

eureka:
  client:
    #registerWithEureka: false
    #fetchRegistry: false
    #preferIpAddress: true
    register-with-eureka: false             # Only for local stand-alone development
    fetch-registry: false                   # Only for local stand-alone development
    service-url:
      defaultZone: http://localhost:8761/eureka  # Default Value. Just for demo
  server:
      #waitTimeInMsWhenSyncEmpty: 0
      response-cache-update-interval-ms: 1000 # Eureka Server's Response Cache. Default 30,000ms
      enableSelfPreservation: false           # Just for demo